# <span style="color:darkblue"> Lecture 12: Application 2 - Random Assignment </span>

<font size = "5">

# <span style="color:darkblue"> I. Import Libraries and Data </span>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
carfeatures = pd.read_csv("data_raw/features.csv")

# <span style="color:darkblue"> I. Random Assignment </span>

<font size = "5">

Random assignment is crucial for scientific progress ...

- The basis for medical trials
- Also used in engineering, the natural sciences and <br>
  social sciences (economics, political science, etc.)

In [3]:
# "list_status" is a list with "treatment/control" arms
# "prop_status" is the proportion in the treatment and control arms
# "size_dataset" is how many rows are contained

list_status  = ["Treatment","Control"]
prop_status  = [0.4,0.6]
size_dataset = len(carfeatures)

<font size = "5">
Random assignment

In [4]:
# The "np.random.choice" will create a vector with the status
# We will save this to a column in "carfeatures"
# Note: (i) We can always split the arguments of a function in multiple lines
#           to make it easier to read
#       (ii) 

carfeatures["status"] = np.random.choice(list_status,
                                         size = size_dataset,
                                         p = prop_status)

display(carfeatures)

,mpg,cylinders,displacement,horsepower,weight,acceleration,vehicle_id,status
0,18.0,8,307,130,3504,12.0,C-1689780,Treatment
1,15.0,8,350,165,3693,11.5,B-1689791,Treatment
2,18.0,8,318,150,3436,11.0,P-1689802,Treatment
3,16.0,8,304,150,3433,12.0,A-1689813,Treatment
4,17.0,8,302,140,3449,10.5,F-1689824,Treatment
...,...,...,...,...,...,...,...,...
393,27.0,4,140,86,2790,15.6,F-1694103,Control
394,44.0,4,97,52,2130,24.6,V-1694114,Control
395,32.0,4,135,84,2295,11.6,D-1694125,Control
396,28.0,4,120,79,2625,18.6,F-1694136,Treatment
397,31.0,4,119,82,2720,19.4,C-1694147,Control

<font size = "5">

Compute frequencies by status

In [5]:
# The command "pd.crosstab" computes frequencies
# If we add the option "normalize" it will compute proportions
# Note: The default assignment is done randomly without replacement
#       which means that the proportions are approximately the same   
#       (but not equal) to "prop_status"

frequency_table   = pd.crosstab(index = carfeatures["status"], columns = "Frequency")
proportions_table = pd.crosstab(index = carfeatures["status"],
                                columns = "Frequency",
                                normalize = True)

display(frequency_table)
display(proportions_table)

col_0      Frequency
status
Control          242
Treatment        156

col_0      Frequency
status
Control      0.60804
Treatment    0.39196

<font size = "5">

Query with string conditions

In [7]:
# When you have queries for text variables, it's important
# to use outer ' ' single quotations
# and inner double quotations.

data_treated = carfeatures.query('status == "Treatment" ')
data_control = carfeatures.query('status == "Control" ')

<font size = "5">

Treated/control should be similar

- This is the key principle of random assignment
- We can check the summary statistics

In [8]:
# The count is different because we assigned different proportions
# All other sumary statistics are approximately the same
# They are not identical because the assignment is random

display(data_treated.describe())
display(data_control.describe())

             mpg   cylinders  displacement       weight  acceleration
count  156.00000  156.000000    156.000000   156.000000    156.000000
mean    23.36859    5.602564    201.442308  3029.230769     15.397436
std      8.19030    1.728992    105.160599   868.469725      2.643164
min     10.00000    3.000000     70.000000  1613.000000      9.500000
25%     17.00000    4.000000    105.000000  2219.750000     13.500000
50%     21.50000    6.000000    177.000000  2945.000000     15.150000
75%     30.00000    8.000000    302.000000  3642.000000     17.025000
max     46.60000    8.000000    429.000000  4997.000000     24.800000

              mpg   cylinders  displacement       weight  acceleration
count  242.000000  242.000000    242.000000   242.000000    242.000000
mean    23.608678    5.359504    188.260331  2932.516529     15.678099
std      7.580700    1.679413    103.578675   832.210954      2.828995
min      9.000000    3.000000     68.000000  1755.000000      8.000000
25%     17.500000    4.000000     98.500000  2226.500000     14.000000
50%     23.000000    4.000000    140.000000  2759.500000     15.500000
75%     28.950000    6.000000    256.000000  3561.250000     17.275000
max     44.000000    8.000000    455.000000  5140.000000     24.600000

## <span style="color:darkblue"> III. Quiz Structure </span>

<font size = "5">

The day of the quiz I will ...
- Provide a dataset with information
- Give more specific instructions.
- Below, you will see the type of questions that will be asked.
- The idea is for you to apply known concepts to new data
- You have 50 minutes to complete the assignment

Questions

(exact wording may change in quiz, but exercise will be very similar)

<font size = "5">

(a) Create a function and apply it to a column

- Check Lecture 8 for how to define a function
- The function will have if/else statements and output a string
- You will use ".apply()" to create a new variable in the dataset <br>
(see Lecture 9)

In [ ]:

# Using if/else to create a function
def fn_numeric_grade(grade):
    if (grade >= 55):
        status = "pass"
    else:
        status = "fail"
    return(status)
print(fn_numeric_grade(54))

# Using .apply() to create a new variable in the dataset
# ignore lambda, use if/else function name
# read the csv dataset
# create the fuction with if/else
# datasetname["chosen name for variable"] = datasetname["column name"].apply(created function)
dataset = pd.read_csv("data_raw/features.csv")
big_mpg = lambda mpg: mpg >= 29
dataset["mpg_above_29"] = dataset["mpg"].apply(big_mpg)

<font size = "5">

(b) Use queries + global variables

- You will be asked to compute certain summary statistics <br>
(mean, median, etc)
- The query will have multiple conditions
- Then subset a dataset that meets certain conditions
- See Lecture 10 for more details

In [ ]:
# computing a summary statistic then using a query
# can use & sign for multiple conditions
mean_mpg = carfeatures["mpg"].mean()
carfeatures.query("mpg >= @mean_mpg")

<font size = "5">

(c) Use sorting + ".loc[]"

- Extract the observations with the largest values of a column
- See Lecture 10 for details

In [ ]:

car_ascendingmpg = carfeatures.sort_values(by = "mpg", ascending = False)
display(car_ascendingmpg.iloc[0:5,:])

<font size = "5">

(d) Split a dataset into subsets

- You will be asked to randomly assign a status to each row
- Split the data into separate datasets using ".query()"
- This will closely follow the material in Lecture 12 (this one)
- You will need this result to answer questions (e), (f)

In [ ]:
# prop_status is the proportion of treatment vs control groups
# size_dataset uses len function to determine number of rows
list_status  = ["Treatment","Control"]
prop_status  = [0.4,0.6]
size_dataset = len(carfeatures)

# assign random status
carfeatures["status"] = np.random.choice(list_status,
                                         size = size_dataset,
                                         p = prop_status)

display(carfeatures)

data_treated = carfeatures.query('status == "Treatment" ')
data_control = carfeatures.query('status == "Control" ')

<font size = "5">

(e) Create a function with four inputs $f(y,x,b0,b1)$

- Start by using "def" to define the function
- The function will include arithmetic operations (Lecture 3) <br>
and summary statistics for pandas (mean, std, min, max, etc.)
- You will be asked to test different values of $(y,x,b0,b1)$
- You will get $y$ and $x$ from the two datasets in part (d)
- Note: You will **not** be required to use the "statsmodels" library

In [ ]:
# def to define function
def fn_compute_value(y,x,b0,b1):
    Fx = y + x + b0 + b1
    return(Fx)
Fx1 = fn_compute_value(y = 1000, x = 0.01, b0 = 20, b1 = 10)

<font size = "5">

(f) Create two overlapping histogram plots

- You will use a variable from the two datasets in (d)
- You need to use the "alpha" option to make the graphs semitransparent
- You will need to add a legend, label the axes, and the title
- Note: The goal of this question is to illustrate that random <br>
assignment produces very similar distributions between two groups

In [ ]:
list_unique_cylinders = pd.unique(carfeatures["cylinders"])

for category in list_unique_cylinders:
    df   = carfeatures.query("cylinders == @category")
    plt.hist(x = df["mpg"], alpha = 0.5)
    
# Add labels and a legends    
plt.xlabel("Weight")
plt.ylabel("Acceleration")
plt.legend(labels = list_unique_cylinders,
           title  = "Cylinders")
plt.show()

# method 2
plt.scatter(x = dataset["x"], y = dataset["y"])
plt.scatter(x = dataset["x"], y = dataset["p"])

plt.xlabel("X Variable")
plt.ylabel("Y Variable")
plt.title("Blah")
plt.legend(labels = ["Data points", "Best fit line"])
plt.show()